version: "3"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gawasa
      POSTGRES_PASSWORD: gawasa
      POSTGRES_DB: gawasa
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data:
